# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'bold 10pt Terminus'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '10pt Terminus'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '10pt Terminus'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '10pt Terminus'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 12pt Terminus'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '10pt Terminus'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '10pt Terminus'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '10pt Terminus'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '10pt Terminus'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = '"xos4 Terminus", Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '10pt sans-serif'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt Terminus'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = 'bold 12pt Terminus'
